---
- hosts: localhost
  become: no
  vars_prompt:
    - name: yn_gpu
      prompt: "Do you install GPU modules(cuda: 10.2, cudnn: 7.6.5, TensorRT: 7.0.0)? (y/n)"
      default: "y"
      private: no
  roles:
    - { role: cuda, when: yn_gpu == 'y', tags: ["cuda"] }
    - { role: tensorrt, when: yn_gpu == 'y', tags: ["tensorrt"] }
    - { role: ros, vars: { rosdistro: noetic }, tags: ["ros"] }
    - { role: osqp, tags: ["osqp"] }
    - { role: autoware, tags: ["autoware"] }
