---
# https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing
- name: TensorRT (install machine learning repository)
  become: yes
  apt:
    # Use 1804 instead because 2004 seems not working now(20201012)
    deb: https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb

- name: TensorRT (install libraries for TensorRT 8)
  become: yes
  apt:
    name:
      - libcudnn8=8.0.2.39-1+cuda11.0
      - libcudnn8-dev=8.0.2.39-1+cuda11.0
      - libnvinfer7=7.2.0-1+cuda11.0
      - libnvinfer-dev=7.2.0-1+cuda11.0
      - libnvinfer-plugin7=7.2.0-1+cuda11.0
      - libnvinfer-plugin-dev=7.2.0-1+cuda11.0
      - libnvonnxparsers7=7.2.0-1+cuda11.0
      - libnvonnxparsers-dev=7.2.0-1+cuda11.0
      - libnvparsers7=7.2.0-1+cuda11.0
      - libnvparsers-dev=7.2.0-1+cuda11.0
    update_cache: yes

- name: TensorRT (prevent cuda related packages from upgrading)
  become: yes
  command: apt-mark hold "{{ item }}"
  with_items:
    - nvidia-machine-learning-repo-ubuntu1804
    - cuda-11-0
    - libcudnn8
    - libcudnn8-dev
    - libnvinfer7
    - libnvinfer-dev
    - libnvinfer-plugin7
    - libnvinfer-plugin-dev
    - libnvonnxparsers7
    - libnvonnxparsers-dev
    - libnvparsers7
    - libnvparsers-dev
