---
- name: Autoware (install pip)
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
  become: yes

- name: Autoware (install gdown to download some files for neural network)
  pip:
    name:
      - gdown

- name: Autoware (install geographiclib-tools)
  apt:
    name: geographiclib-tools
    state: latest
    update_cache: yes
  become: yes

- name: Autoware (install egm2008-1)
  shell: geographiclib-get-geoids egm2008-1
  become: yes

- name: Autoware (install python-is-python3)
  apt:
    name: python-is-python3
    state: latest
    update_cache: yes
  become: yes

- name: Autoware (install gcc/g++ 9)
  apt:
    name:
      - gcc-9
      - g++-9
    state: latest
    update_cache: yes
  become: yes

- name: Autoware (update-alternatives gcc)
  alternatives:
    link: /usr/bin/gcc
    name: gcc
    path: /usr/bin/gcc-9
    priority: 9
  become: yes

- name: Autoware (update-alternatives g++)
  alternatives:
    link: /usr/bin/g++
    name: g++
    path: /usr/bin/g++-9
    priority: 9
  become: yes
