---
name: ci
on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: brew install hadolint && hadolint ./Dockerfile

      - name: Build docker image
        run: docker build .
